### ISSUE TITLE
Add circleci configuration and fix tox errors

### ISSUE THREAD

**Issue by knobotz** [deeplearninc/relaax#89]
Tested this locally, it should work to just create a file called `.circleci/config.yml` that has the following content:

```yaml
version: 2
jobs:
  build:
    working_directory: ~/relaax
    docker:
      - image: circleci/python
    steps:
      - checkout
      - restore_cache:
          key: relaax-{{ arch }}-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
      - run:
          command: |
            sudo apt-get -qq update
            sudo apt-get -qq -y install python-dev
      - run:
          command: sudo pip install tox
      - run:
          command: tox
      - save_cache:
          key: relaax-{{ arch }}-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
          paths:
            - ".tox"
```

The `tox` build needs to pass first though. Currently it reports a lot of lint errors when it runs `flake8`.
